server:
 port: 8085
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  password: root
  url: jdbc:mysql://localhost:3306/short_video
  username: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update

eureka:
  client:

    service-url:
      defaultZone: http://localhost:8555/eureka/